### ISSUE TITLE
BaseWindow and WindowConfig instances reference each other

### ISSUE THREAD

**Issue by nir** [moderngl/moderngl-window#105]
BaseWindow and WindowConfig instances reference each other.

Here are links to the relevant lines in the code:

https://github.com/moderngl/moderngl-window/blob/5cf117ca9c0ef8cbde772d51041a039fc611b6c7/moderngl_window/context/base/window.py#L397

https://github.com/moderngl/moderngl-window/blob/5cf117ca9c0ef8cbde772d51041a039fc611b6c7/moderngl_window/context/base/window.py#L862

https://github.com/moderngl/moderngl-window/blob/5cf117ca9c0ef8cbde772d51041a039fc611b6c7/moderngl_window/__init__.py#L193

**Comment by einarf** [comment]
Fixed in 6a6b201da07c1e70dbdd339fa6f436a8cc299c3f
