### ISSUE TITLE
Add an option to have the 0, 0 coordinate designate the bottom left corner

### ISSUE THREAD

**Issue by nir** [moderngl/moderngl-window#106]
In mouse events, the 0, 0 coordinate designates the upper left corner. 

Contemplating this, it occurs to me that for windowing systems having the 0,0 on the upper left makes sense, since (a) windows are traditionally resized by pulling their bottom right corner, and since (b) their output grows from top to bottom for textual output at least.

for gaming though, naively thinking about this (since I'm new to this) 0, 0 makes sense on the bottom left, since if you place a (2d) object on top of another, you expect it to work from the ground up
in terms of coordinates.

Adding an option to flip the coordinate system upside down as you proposed would be great.

**Comment by einarf** [comment]
Might be able to solve two problems

* When using fixed aspect ratio the system will add black borders horisontally or vertically if the window size do not match the configured aspect ratio
* Having the ability to change the origin of the mouse coordinate system.

After a bit of thinking the less intrusive solution would be to add a method in the window that will do both of these conversions possibly with a `flip_y` optional argument.

**Comment by einarf** [comment]
We now have `Window.convert_window_coordinates` for this.
