### ISSUE TITLE
Add configuration to scale glfw window to monitor

### ISSUE THREAD

**Issue by nir** [moderngl/moderngl-window#117]
Currently MGLW GLFW windows ignore monitor scaling (On Windows 10, it is the Scale and Layout setting of the Display settings).

In conversation Einar proposed setting the following flag which indeed does the trick:

glfw.window_hint(0x0002200C, True)

0x0002200C corresponds to the following flag: GLFW_SCALE_TO_MONITOR

**Comment by einarf** [comment]
Thanks. I think we might get away by always setting this, but this needs to be properly tested first. Should be easy enough to solve.

**Comment by einarf** [comment]
Fixed in bb60fea
