### ISSUE TITLE
window config close() function not called in case of glfw

### ISSUE THREAD

**Issue by nir** [moderngl/moderngl-window#118]
Add the following method to the ModernglLogo class in the moderngl_logo.py example:

    def close(self):
        print('bye, bye')

Run the example and click the red [x] button on the top-right of the window.

In case of pyglet the string 'bye, bye' will be printed on screen.
In case of glfw the string will not be printed.

**Comment by einarf** [comment]
Fixed in d86edffa512e51f2da0ba3d6fb1ff336e480577d
