### ISSUE TITLE
Draw events not dispatched during resize

### ISSUE THREAD

**Issue by ShaunKulesa** [moderngl/moderngl-window#122]
When i resize the window everything inside goes black.

https://user-images.githubusercontent.com/69469909/105535849-4fbe3b80-5ce7-11eb-8046-e3dd3e5bd1d0.mp4

**Comment by einarf** [comment]
This needs to be looket at per window. Normally event pulling blocks or buffers should be swapped in resize. Some libraries like SDL2 have event filters as well.

**Comment by einarf** [comment]
SDL2: https://stackoverflow.com/questions/34967628/sdl2-window-turns-black-on-resize

**Comment by einarf** [comment]
Closing this for now. It's really up to the window libraries. We don't really control much for this.
