### ISSUE TITLE
OSX: Framerate go crazy when window is minimized or hidden

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl-window#123]
We need something to throttle the framerate when a window is minimized or hidden. Preferably something configurable.

Two other problems with vsync:
* While calling `swap_buffers` other threads will stall
* Might not play well with asyncio

Could be that we need an alternative to vsync as well.

**Comment by einarf** [comment]
Need to look into what window events we can use here. This is mainly hide/show (iconify) and focus/unfocus

* Pyglet : `on_activate` `on_deactivate`
*

**Comment by einarf** [comment]
Not even going to touch this one.

**Comment by Peter0923** [comment]
I meet the same issue that the FPS keeps in 2600+ when window is hidden and the battery is consumed fast.
How this gets solved?

Regards,
Peter

**Comment by einarf** [comment]
What platform and window backend? Would enforcing vsync be a solution?

**Comment by Peter0923** [comment]
Apple M1 Pro, Sonoma 14.5
moderngl             5.10.0
moderngl-window      2.4.4
pyglet               2.0.15
I already enabled vsync as True but that doesn't work.

**Comment by einarf** [comment]
Fixed in master. `WindowConfig.hidden_window_framerate_limit` should now limit framerate when the window is hidden. It can be disabled by setting it to 0.
