### ISSUE TITLE
frame_time passed to render() can be < 0

### ISSUE THREAD

**Issue by rjbudzynski** [moderngl/moderngl-window#129]
To demonstrate: insert 

```
if frame_time < 0:
    print(f'Frame {self.nframes}: frame_time = {frame_time}')
```

at the top of `def render(...)` in [conways_game_of_life.py](https://github.com/moderngl/moderngl/blob/master/examples/conways_game_of_life.py).

Saw the output:

```
Frame 0: frame_time = -1615419377.0747166
```

**Comment by einarf** [comment]
Thanks. That seems to be a bug with one of the `TImer` classes. I've seen a small negative value in the first frame.. but obviouslty such a big delta is a much bigger problem than I expected.

**Comment by einarf** [comment]
Fixed
