### ISSUE TITLE
Support for compilation

### ISSUE THREAD

**Issue by XReaper95** [moderngl/moderngl-window#131]
Hi, first of all, thank you all contributors for this great project! So, my problem is that I'm trying to create a standalone executable of a project that uses this (using [Nuitka](https://github.com/Nuitka/Nuitka) if that matters). All is compiled successfully, but there is a very tiny problem, there is this function in the package `__init__.py`:

```python
def find_window_classes() -> List[str]:
    """
    Find available window packages

    Returns:
        A list of available window packages
    """
    return [
        path.parts[-1]
        for path in Path(__file__).parent.joinpath("context").iterdir()
        if path.is_dir() and path.parts[-1] not in IGNORE_DIRS
    ]
```

As far as I understand it is reading the file system looking for packages inside the `context` directory, just to create this helper argument list from `-wnd` command line option:

```bash
usage: main.py [-h] [-wnd {pyside2,pyqt5,sdl2,glfw,headless,pygame2,pyglet,tk}] [-fs] [-vs VSYNC] [-r RESIZABLE] [-s SAMPLES] [-c CURSOR] [--size SIZE] [--size_mult SIZE_MULT]
main.py: error: argument -wnd/--window: invalid choice: 'aaa' (choose from 'pyside2', 'pyqt5', 'sdl2', 'glfw', 'headless', 'pygame2', 'pyglet', 'tk')
```

Thing is, this crashes during the runtime, as there is no such file system organization! It actually looks like this 

```
moderngl/
    lib1.so
    lib2.so
    ......
other_package/
    lib1.so
    ......
other_lib.so.1
other_lib1.so
   ......
executable
```
If I comment out that function the problem goes away. Is there any way to solve this? Would be bad to have a hardcoded list of windows backends?

**Comment by einarf** [comment]
It would be possible to add some fallback here? Do you simply get an `ImportError` or an empty result?

**Comment by XReaper95** [comment]
Hi, thanks for answering! I actually get `FileNotFoundError: [Errno 2] No such file or directory: '<project_compiled_path>/moderngl_window/context'`, it is expected because of this call in `find_window_classes` -> `for path in Path(__file__).parent.joinpath("context").iterdir()`. And yes a fallback will be the perfect solution, could be a hardcoded list of that context, I'm trying to think of a more dinamic solution, I can do a PR if you don't mind, but it will be later I'm a little busy rn.

**Comment by einarf** [comment]
Sure. A PR would be most practical because you'll be able to verify it working on your side. I would suggest adding a global list of strings called `WINDOW_CLASSES` in `__init__.py` so people can tinker with it. Just replace the current code entirely to use that.

**Comment by XReaper95** [comment]
I made a PR for this #133.

**Comment by einarf** [comment]
Merged and all done
