### ISSUE TITLE
in/out block syntax not supported, can't override and pass `varyings`

### ISSUE THREAD

**Issue by anentropic** [moderngl/moderngl-window#134]
Using moderngl-window, I have something like:

```python
        self.prog = self.load_program(
            vertex_shader="shaders/vertex.glsl",
            geometry_shader="shaders/geometry.glsl",
        )
        self.debug_prog = self.load_program(
            vertex_shader="shaders/debug_vertex.glsl",
            fragment_shader="shaders/fragment.glsl",
        )

        self.prog_data = self.ctx.buffer(reserve=data_buffer_size)
        self.debug_buffer = self.ctx.buffer(reserve=data_buffer_size)
        self.debug_vao = self.ctx.vertex_array(
            self.debug_prog,
            [(self.prog_data, "f 2f", "textureId", "gridCoord")],
        )

        self.vao = self.ctx.vertex_array(
            self.prog,
            [(self.debug_buffer, "2f 2f i", "gridCoord", "uv", "textureId")],
        )
```
and in the geometry shader I've used block syntax:
```glsl
in VS_OUT
{
    vec2 gridCoord;
    vec3 pos;
    flat int textureId;
} gs_in[];

out GS_OUT
{
    vec2 gridCoord;
    vec2 uv;
    flat int textureId;
} gs_out;
```
(I'm trying to inspect the output of the geometry shader and then render my fragments as usual)

When I try to run this I get:
```
  File "/demo.py", line 314, in render
    self.debug_vao.transform(
  File "/lib/python3.9/site-packages/moderngl/vertex_array.py", line 233, in transform
    self.mglo.transform(buffer.mglo, mode, vertices, first, instances, buffer_offset)
moderngl.error.Error: the program has no varyings
```

I can see the reason is that the block syntax for in/out vars is not parsed by this regex:
https://github.com/moderngl/moderngl-window/blob/820b7d7c6d4faea3cff2637a150c91582096557b/moderngl_window/opengl/program.py#L358

confirmed via ipdb:
```
ipdb> from moderngl_window.loaders.program.separate import Loader
ipdb> from moderngl_window.meta import ProgramDescription
ipdb> pd = ProgramDescription(vertex_shader="shaders/vertex.glsl", geometry_shader="shaders/geometry.glsl")
ipdb> loader = Loader(pd)
ipdb> geo_source = loader._load_shader("geometry", loader.meta.geometry_shader)
2021-04-01 19:51:15,370 - moderngl_window.loaders.program.separate - INFO - Loading: /resources/shaders/geometry.glsl
ipdb> vs_source = loader._load_shader("vertex", loader.meta.vertex_shader)
2021-04-01 19:51:43,362 - moderngl_window.loaders.program.separate - INFO - Loading: /resources/shaders/vertex.glsl
ipdb> from moderngl_window.opengl import program
ipdb> shaders = program.ProgramShaders.from_separate(pd, vs_source, geometry_source=geo_source)
ipdb> shaders.geometry_source
<ShaderSource: shaders/geometry.glsl id=0>
ipdb> shaders.geometry_source.find_out_attribs()
[]
ipdb> shaders.vertex_source.find_out_attribs()
[]
```

Which is ok, there seems to be no good GLSL parser module for Python, and trying to cover more syntax with a regex will not be fun.

I can see I have a couple of options:

- don't use block syntax in the shaders
- don't use `WindowConfig.load_program` and instead load the shader source myself and pass it as a string to `self.ctx.program` method which accepts the `varyings` arg

Perhaps it would be useful if there was a way to manually override the varyings in moderngl-window interface though?

**Comment by einarf** [comment]
I definitely support adding this. The introspection is very naive. Adding a `varyings` parameter to override is a must.

There are a few more issues as well. Might end up simplifying the whole thing. It was a bit too ambitious to start with and it just ends up adding "hidden magic" that ends up being counter-productive.

Thanks for the reminder. It should be fairly quick to add.

**Comment by anentropic** [comment]
I have a question, is the order of the names in "varyings" significant?

Does it have to match the order they are defined in the shaders?

**Comment by anentropic** [comment]
Also... if we had a robust parser, how should these "block" inputs and outputs look to moderngl ?

And do we only care about outputs for "varyings"?

I have been experimenting with the "glsl" rust crate and its AST represents the block as a single in/out with multiple fields like a struct.

Would it need more work to support that (in terms of memory layout etc) on the moderngl side? More than just having the flattened string name extracted I mean.

**Comment by einarf** [comment]
Think I might try to breathe some life into this one again
https://github.com/rougier/glsl-parser

When it comes to blocks I don't really remember. Will have to try it out 😄

**Comment by anentropic** [comment]
I'd been wanting to have a play with PyO3 for a while, so I put something together quickly:
https://github.com/anentropic/python-glsl-shaderinfo

...if it looks like being useful, let me know and I can put a bit more effort into it :)

**Comment by einarf** [comment]
Nice one. I have no idea what is best at the moment. I am very careful about adding new dependecies as these do require maintenance as well.

**Comment by einarf** [comment]
Fixed in master: You can now pass in `varyings` when loading a program overriding the auto detected ones. We still need to improve the auto detection, but this is a step forward.
