### ISSUE TITLE
Wrong key mapping in glfw

### ISSUE THREAD

**Issue by wk39** [moderngl/moderngl-window#138]
Could you please correct errata?

F10/F11 both keys are mapped to glfw F11

context/glfw/keys.py

`F10 = glfw.KEY_F11`
`F11 = glfw.KEY_F11`

Thank you.

**Comment by einarf** [comment]
Derp. Thank you for reporting.

**Comment by einarf** [comment]
Fixed in 5067c15

**Comment by wk39** [comment]
Thank you!
