### ISSUE TITLE
Moving window is laggy

### ISSUE THREAD

**Issue by wk39** [moderngl/moderngl-window#141]
It's not a big issue, but dragging window is laggy. (glfw)
I'm not sure it is moderngl-window issue but other GL programs(non-python) have no problem.
Thank you.

**Comment by einarf** [comment]
What platform? Could it also be vsync thing were the application runs at rally high framerates?

**Comment by wk39** [comment]
I'm using xfce4 (xubuntu) on ubuntu 18.04.
I have just check it on Gnome environment and I found no issue. (lag is very small)
"render()" function is blocked while window is moving in xfce4 but runs well in Gnome. 

It should be WM(xfce4) problem...
If no action could be done in moderngl-window, could you close this issue?

Thanks for your response!

**Comment by einarf** [comment]
That sounds like the window manager blocks rendering when moving the window. I don't think there is anything we can do on moderngl-window side. Possibly something that could be done in glfw itself?

**Comment by wk39** [comment]
https://github.com/glfw/glfw/issues/1016
I found related issue but still open. (glfw + nvidia proprietary driver + xfce)

workaround
xfce4 menu > Window Manager Tweak > Compositor (disable it)
render() function still blocked but window can move smoothly.

Thank you!
