### ISSUE TITLE
Intercept close window button (aka ALT + F4 or similar on other platforms)

### ISSUE THREAD

**Issue by wk39** [moderngl/moderngl-window#143]
Hello,
Using imgui and glfw, I want to add quit confirm dialog.
For the key input (ESC or Q) I can use it by key event,
But I can't find how to handle window "x" button pressed.

**Comment by einarf** [comment]
As discussed on discord there is a way to intercept the close event. Not sure how other window libraries handle this. More research needed.

https://www.glfw.org/docs/3.3/window_guide.html

> When the user attempts to close the window, for example by clicking the close widget or using a key chord like Alt+F4, the close flag of the window is set. The window is however not actually destroyed and, unless you watch for this state change, nothing further happens.
> The current state of the close flag is returned by glfwWindowShouldClose and can be set or cleared directly with glfwSetWindowShouldClose. A common pattern is to use the close flag as a main loop condition.

**Comment by einarf** [comment]
The glfw backend supports this now. Need to look into other window libraries

**Comment by einarf** [comment]
Closing this for now. The user should be able to block the close event if needed
