### ISSUE TITLE
How to resize/move Window while executing other scripts/functions?

### ISSUE THREAD

**Issue by bva99** [moderngl/moderngl-window#145]
### Firstly:
I would like to wholeheartedly thank the devs for this great package (and also moderngl)!

### Disclaimer:
I am _really_ new to OpenGL and "windows" (i.e. GUI codes).

### My goal:
Write a class that plots something after creating a window and using `vao.render(mode=moderngl.PATCHES)` only when an `update()` method is called, in order to update a dynamic VBO. `imshow` by matplotlib is just toooo slow.

### The issue:
I cannot resize/move/close the window when other python codes are running.

### What I've done:
Based on einarf's tips on #114, [moderngl #216](https://github.com/moderngl/moderngl/issues/216) and on many examples, I created a custom window setup that does not have a `run()` method. Instead, a VAO (which is an attribute of the class) is rendered when the class is initialized. Then an `update(inputs)` method may be used to change a dynamic VBO (also an attribute) by using `self.vbo.write(inputs)` and the VAO is re-rendered, followed by a `swap_buffers()` call.

### The question:
Is there a simple way to "fix" this issue?

I can see two ways of achieving this by other means, but I don't have enough knowledge to do them without at least a week of intensive studying. They are:
1- Learn how to use the `thread` library. Run all objects of my class in a single "plotting" thread. This way I can continuously `run()` the objects without blocking other python codes from running. This would mean I would be able to always interact with all opened windows. Though, I would have to figure out how to pass data from the other threads to this plotting thread and then `run()` all objects sequentially.
2- Implement a function analogous to `matplotlib.pyplot.show()`. This would mean that at the end of all the computations I would be able to interact with all opened windows. Though, I have no idea how to maintain a list of all active objects of my class and `run()` them all sequentially.

### Meta question:
I'm not sure if I should have opened this issue here or asked in StackOverflow. What do you prefer? I can close this and re-write it there, if it would be more appropriate.

**Comment by einarf** [comment]
> I cannot resize/move/close the window when other python codes are running.

This really depends on the details. The window main loop needs to keep running or the window will become inactive. What is this "other python code"? If it's something fairly light it can be done in the window main loop. Otherwise you would ideally want to have the long running python code in a subprocess and transfter the new data into the main process for displaying (when the data is ready)

**Comment by bva99** [comment]
> What is this "other python code"?

It involves a series of multithreaded sparse direct solvers. Among other things.

> Otherwise you would ideally want to have the long running python code in a subprocess and transfter the new data into the main process for displaying (when the data is ready)

I see. I guess I'll have to study `thread` then. Or `multiprocessing` even. Do you have any tips, please? (Btw, is this where "asynchronous execution" would be applied?)

**Comment by einarf** [comment]
A very ugly script starting a `Process`. We use a `Queue` to read data from the process itself. Might be overkill attempting to get data from the queue every frame.

```py
import time
import multiprocessing
from queue import Empty
import moderngl_window

queue = None
process = None

class App(moderngl_window.WindowConfig):
    title = "Subprocess Testing"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def render(self, time: float, frame_time: float):
        try:
            data = queue.get(block=False)
            print("New data arrived:", data)
        except Empty:
            pass

    def close(self):
        process.terminate()


def background_work(q):
    while True:
        q.put('hello')
        time.sleep(1)


if __name__ == "__main__":
    queue = multiprocessing.Queue()
    process = multiprocessing.Process(target=background_work, args=(queue,))
    process.start()
    App.run()
```

**Comment by bva99** [comment]
Thank you very much einarf!

In the meantime, I tried out my 2nd idea from the original post. I created a class attribute that keeps track of all instantiated objects and then made a static method that runs all of the opened windows simultaneously.

It *does* work, but the windows are a bit unresponsive. For example, after calling `myViewerClass.show_all()` I need like 2 or 3 attempts to resize a window, since it seems to periodically ignore my mouse clicks. And a window doesn't close when I click on it. Instead, it freezes. The other windows continue functioning. Only after clicking on the close button of all windows do they all close.

In your script am I able to simultaneously keep more than one window open? I'll try your script out and have study it more carefully.

```python
# to illustrate the main packages I actually use, they are written here
import numpy as np
import moderngl
import moderngl_window
from moderngl_window.conf import settings


class myViewerClass:

    # A dict as a mutable class attribute to keep track
    # of all instances of this class
    _manager_dict = {}

    def __init__(self):  # there can be more inputs here

        # more code here, properly initializing the window using
        # moderngl_window.conf.settings

        # if no instances of this class exists yet
        if not myViewerClass._manager_dict:
            # assign a key of 0 to the first instance of this class
            self._num = 0
        else:
            # else, assign a distinct integer greater than the maximum
            # one found in the dict's keys
            self._num = max(myViewerClass._manager_dict.keys())+1
        # save an alias of the generated object in the dict
        myViewerClass._manager_dict[self._num] = self

    @staticmethod
    show_all():
        # run while there are still open windows
        # this works because the dictionary evaluates to True
        # while it is not empty
        while myViewerClass._manager_dict:
            for window in myViewerClass._manager_dict.values():
                window.wnd.clear()  # this is from moderngl_window
                window.render()  # this is an instance method that is
                                 # implemented in this class using
                                 # OpenGL (ModernGL)
                window.wnd.swap_buffers()  # also from moderngl_window
                if window.wnd.is_closing():
                    # delete this object's entry in the class dict
                    del myViewerClass._manager_dict[window._num]
                    # close the window
                    window.wnd.destroy()
                    break  # this is necessary because the dict's
                           # length has changed, which issues an
                           # error in the `for` loop
```

**Comment by einarf** [comment]
The original issue did not include multiple windows. That complicates things a lot.

**Comment by bva99** [comment]
Ah, I see. Should I close this issue and open a new one?

**Comment by einarf** [comment]
Closing this for now.
