### ISSUE TITLE
Window getting maximized at creation

### ISSUE THREAD

**Issue by Rafale25** [moderngl/moderngl-window#156]
If I create a 1500 by 1080 window for example on my 2560x1440 screen, the window open at the size specified
But if i set the window to 1600x1080, then it get maximized when starting the program

Looks like it's happening only on Linux

**Comment by einarf** [comment]
Did we figure this out?

**Comment by einarf** [comment]
Will assume a more recent glfw version solved this or it was something related to scaling locally
