### ISSUE TITLE
allow to manage pygame2 USEREVENT

### ISSUE THREAD

**Issue by cubr3** [moderngl/moderngl-window#162]
Hi,

Would you consider to add a quick fix like the following at the end of  `moderngl_window.context.pygame2.window.Window.process_events()` as you grab **all** events including pygame2 **USEREVENT** that could be excluded from the unified system (non standard events) ?

Proposal 1: simple
```
    def process_events(self) -> None:
        """Handle all queued events in pygame2 dispatching events to standard methods"""

        for event in pg.event.get():
            if event.type == pg.MOUSEMOTION:
                self._handle_mods()
            ...
            elif event.type == pg.USEREVENT:
                self.process_user_event(event)
```

or perhaps better

Proposal 2: more open solution 
```
    def process_events(self) -> None:
        """Handle all queued events in pygame2 dispatching events to standard methods"""

        for event in pg.event.get():
            if event.type == pg.MOUSEMOTION:
                self._handle_mods()
            ...
            else:
                self.process_custom_event(event)
                # or self.process_non_standard_event(event) ?
                # or self.process_non_unified_event(event) ?
```

today, we have to *copy/paste* whole `process_events` method in a new class that inherits from `moderngl_window.context.pygame2.window.Window`. Not fan of copy/paste design.

references: 
- [Pygame USEREVENT](https://www.pygame.org/docs/ref/event.html#pygame.event.custom_type)
- [Examples](https://github.com/search?q=pygame.event.custom_type&type=Code&l=Python)

**Comment by einarf** [comment]
You can actually subclass a window and configure that window class in the settings module.

Maybe method 1 is better since it will be custom for pygame. The callback could be called `on_generic_event` for example? That way we could funnel all non-processed events for all window types into this one.

**Comment by einarf** [comment]
Should be in 2.4.2
