### ISSUE TITLE
Pygame2 error: 'Event' object has no attribute 'state'

### ISSUE THREAD

**Issue by PycraftDeveloper** [moderngl/moderngl-window#165]
When using Pygame2 for the window class the error: 'Event' object has no attribute 'state' occurs.

This is because in 'window.py' in the 'pygame2' folder; found here: https://github.com/moderngl/moderngl-window/blob/master/moderngl_window/context/pygame2/window.py line 285 is causing problems, there is no attribute 'state' in the 'event' object.

Without knowing its exact function, simply commenting it out fixes the problem and using Pygame2 for the window class works fine again.

![Untitled2](https://user-images.githubusercontent.com/81379254/184127053-7d560416-7ab5-44b7-88a3-c6f6757d123b.png)

![download2](https://user-images.githubusercontent.com/81379254/184127550-1611de8d-98a9-453a-905e-46c6a3fc80c6.png)

![download3](https://user-images.githubusercontent.com/81379254/184128031-c2c8c12a-4d1f-4881-88f7-6b377d0eac2a.png)

**Comment by einarf** [comment]
What pygame version are you using? It was originally created for a dev release of 2.0 so we might need to bump that one.

**Comment by PycraftDeveloper** [comment]
I am using Pygame version: 2.1.2, I hope that helps!

**Comment by einarf** [comment]
Right. I made this window backend back in 2.0.0dev days and it probably needs some updating. I didn't know there was breaking changes in events.

**Comment by PycraftDeveloper** [comment]
Ah ok, it doesn't look too challenging to fix, I was able to work around it by simply commenting out a small section of code to fix the error, but that isn't probably an ideal solution! Hopefully this isn't a difficult fix, thanks also for the quick response!

**Comment by einarf** [comment]
Should be fixed in 2.4.2
