### ISSUE TITLE
Pypi source distribution not published for 2.4.2

### ISSUE THREAD

**Issue by pavelzw** [moderngl/moderngl-window#172]
For the 2.4.2 release on pypi, the source distributions are not published. Therefore, the conda package cannot be built since it uses the `.tar.gz` usually provided on pypi.

![image](https://user-images.githubusercontent.com/29506042/222685790-201a722f-ae89-4bdc-90ac-9cdb77a1f646.png)

See https://conda-forge.org/status/
![image](https://user-images.githubusercontent.com/29506042/222685930-dacc3e40-b218-4fa4-91c1-9fd55464c3e6.png)

Could you upload the `.tar.gz` source distribution too?

**Comment by einarf** [comment]
Thanks for the poke. Uploaded now.
