### ISSUE TITLE
Key press event not registered

### ISSUE THREAD

**Issue by alexracape** [moderngl/moderngl-window#175]
When using the newest version of pyglet, only key release events are registered by key_event.

**Comment by einarf** [comment]
2.0.8?

**Comment by alexracape** [comment]
Yes. I tried reverting back to 2.0.7, but it looks like unicode char input isn't registered there. I am inheriting from WindowConfig, and defining event handlers there such as `key_event` and `unicode_char_entered`.

**Comment by einarf** [comment]
I can't reproduce this in a quick test. What platform is this?

**Comment by einarf** [comment]
This might be some bug in pyglet that could need a minial example and reported in the pyglet project? I only have an old intel mac and it works there. They did a refactor recently for M1/2 macs since the event system was completely broken. That's really all I know.

**Comment by einarf** [comment]
https://github.com/pyglet/pyglet/pull/898
