### ISSUE TITLE
PIL versions <10.0.1 vulnerability

### ISSUE THREAD

**Issue by nouturnsign** [moderngl/moderngl-window#178]
moderngl-window currently depends on Pillow version to be >=9 and <10, but a [recent vulnerability](https://security.snyk.io/vuln/SNYK-PYTHON-PILLOW-5918878) was discovered in Pillow, patched in version 10.0.1. 

I am unsure of why the restriction <10 is necessary, and if this version is required, then please disregard this issue.

I would like to bump the version of Pillow my project uses to Pillow 10.0.1, but moderngl-window prevents me from doing so.

**Comment by einarf** [comment]
Thanks. I saw the warning recently. Will do some maintenance and push out new release hopfully in the weekend. Need to check if the pillow upgrade actually affects anything. They moved some transform enums recently. If this is not a problem we can just use `>=` for pillow. I think that might be a good idea for more dependencies.

Other things to look into before release (note to self)
* Look into merging the PyGLM PR
* Rebase and merge the old `pyproject.toml` PR
* Other small lingering issues

That would probably need to be a 3.0 release. might be a good idea to do a 2.x.x with the pillow constraint removed first.

**Comment by einarf** [comment]
Fixed in master branch
