### ISSUE TITLE
Resizing window from within WindowConfig after initialization

### ISSUE THREAD

**Issue by burningion** [moderngl/moderngl-window#179]
Hey,
 
Thanks for all the work on moderngl and moderngl-window. I've been using them both, and they've been great to use.

I have kind of an odd use case, where my viewport and window will change after loading a video. My window will either be 1920x1080, or 1080x1920.

If I manually set the `self.window_size` I don't seem to be able to resize the physical window. I can of course set a resize() function on the user resizing the window, but I can't seem to find a way to resize the window from code.

Is there something I'm missing to do resizing of the window via code after the window has been initialized? (IE from 1920x1080 to 1080x1920)

Thanks!

**Comment by Leterax** [comment]
Here is a mvp of resizing the window :)

```py
import moderngl_window as mglw

class Test(mglw.WindowConfig):
    gl_version = (3, 3)
    window_size = (1280, 720)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def key_event(self, key, action, modifiers):
        # Key presses
        if action == self.wnd.keys.ACTION_PRESS:
            if key == self.wnd.keys.SPACE:
                print("SPACE key was pressed")
                self.wnd.size = (640, 480)

        # Key releases
        elif action == self.wnd.keys.ACTION_RELEASE:
            if key == self.wnd.keys.SPACE:
                print("SPACE key was released")
                self.wnd.size = (1280, 720)

    def render(self, time, frametime):
        ...

# Blocking call entering rendering/event loop
mglw.run_window_config(Test)
```
