### ISSUE TITLE
x is flipped for everything (scene and etc)

### ISSUE THREAD

**Issue by Del1riumpl** [moderngl/moderngl-window#183]
[src.zip](https://github.com/moderngl/moderngl-window/files/13457818/src.zip)
please help

**Comment by einarf** [comment]
The moderngl discord is a far better place to ask for help. Issues here on github are more for bugs and features

**Comment by Del1riumpl** [comment]
> The moderngl discord is a far better place to ask for help. Issues here on github are more for bugs and features

Ok thank you.
