### ISSUE TITLE
How to customize context creation?

### ISSUE THREAD

**Issue by szabolcsdombi** [moderngl/moderngl-window#185]
I would like to customize context creation for moderngl.

The current workaround is to hack on the create context function.

```py
import moderngl_window as mglw
import moderngl

moderngl.create_context = ...
mglw.BaseWindow.init_mgl_context = ...
```

Is there any way to customize context creation from a WindowConfig?

```py

class Example(mglw.WindowConfig):
    gl_version = (3, 3)
    title = "ModernGL Example"
    window_size = (1280, 720)
    aspect_ratio = 16 / 9
    resizable = True

    resource_dir = os.path.normpath(os.path.join(__file__, '../data'))

    # something like:
    def init_mgl_context(self): ... # or similar
```

**Comment by einarf** [comment]
Taking any ideas for making this less hacky.

**Comment by einarf** [comment]
Monkey-patching the `BaseWindow.init_mgl_context()` definitely seems to be the laziest solution here.

Will keep this open in case better ideas turn up.

**Comment by einarf** [comment]
Related https://github.com/moderngl/moderngl-window/issues/130

**Comment by einarf** [comment]
`init_mgl_context` can now be implemented in the `WindowConfig` to override context creation. It should be a static or classmethod.

**Comment by einarf** [comment]
In master
