### ISSUE TITLE
integration imgui image, rendering to background vs imgui window is flipped

### ISSUE THREAD

**Issue by christopher-hsu** [moderngl/moderngl-window#186]
I am using examples/integration_imgui_image.py as an example case but I have my own custom project am doing something similar. In this example if I render the cube to the background it has one orientation but after you do 
Render cube to offscreen texture / fbo i.e.  self.fbo.use()  self.fbo.clear()

the rendered cube in the imgui window is flipped.

How do I get them to be aligned? I have downstream tasks that require these windows to have the same orientation. I would like the imgui windows to be aligned with the background orientation.

![Screenshot from 2024-02-01 12-43-53](https://github.com/moderngl/moderngl-window/assets/33553268/eb862f64-8ce3-4767-8d5b-edd7894e2d37)

**Comment by einarf** [comment]
Right. I think It's how imgui renders opengl textures. It will by default render them as if they are upside-down textures.

**Comment by christopher-hsu** [comment]
yea you are right, took a long time to find out where to flip but in pyimgui. https://pyimgui.readthedocs.io/en/latest/reference/imgui.core.html#imgui.core.image

when you call imgui.image(fbo.glo, size, uv0, uv1)
use the parameters uv0 = (0,1) and uv1 = (1,0)
