### ISSUE TITLE
Suggestion for a Shadow Mapping tutorial that would further explain how ModernGL works

### ISSUE THREAD

**Issue by alizzen** [moderngl/moderngl-window#51]
I was trying to implement shadow mapping in ModernGL by following tutorials in other languages but it seems like ModernGL has its unique style that isn't very similar to other APIs.

[This](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/) is one of the tutorials

I have searched everywhere for something implemented in ModernGL, with no result.

**Comment by alizzen** [comment]
Readers will benefit from this tutorial by understanding how textures work in OpenGL and ModernGL.

**Comment by einarf** [comment]
Definitely a good idea because many people are asking about this.

**Comment by einarf** [comment]
Working example here: https://github.com/moderngl/moderngl-window/blob/master/examples/advanced/shadow_mapping.py

**Comment by einarf** [comment]
<img width="1392" alt="Screenshot 2020-01-07 at 21 01 55" src="https://user-images.githubusercontent.com/5418180/71925274-f5604480-3190-11ea-862b-48a9f01d248e.png">
