### ISSUE TITLE
Improve vsync support

### ISSUE THREAD

**Issue by saltchicken** [moderngl/moderngl-window#54]
I noticed that when trying to set vsync to false in the following example, vsync is still enabled.
```
class Window(mglw.WindowConfig):
    gl_version = (3, 3)
    title = 'Test'
    vsync = False
```
Passing --vsync false via the command line successfully disables vsync for the same context using the default of pyglet.
I also tried both methods with --window glfw and it ignored both and kept vsync enabled.

**Comment by einarf** [comment]
`WindowConfig` doesn't have a `vsync` class attribute, but it could of course be added.

I know glfw has some issues obeying vsync. Need to look into that 😄

**Comment by einarf** [comment]
What platform are you on? On OS X passing `--vsync off` to the glfw window do in fact disable vsync. I suspect maybe on windows you have to configure vsync specifically to obey the application in nvidia and amd panel.

**Comment by einarf** [comment]
Also, is there a specific reason why we should add a `vsync` attribute to the `WindowConfig` class? Without knowing why it's hard to make any decisions.

**Comment by saltchicken** [comment]
I ran the test on Windows 10 and Ubuntu 18.04.

I am turning vsync off so that I can run real-time processing (specifically DSP) in the same thread. With vsync on the window will sleep behind the scenes according to its target FPS.

**Comment by einarf** [comment]
Ok, so that means there definitely is a use case for supporting vsync in `WindowConfig`.

I guess a TODO list might be:
- [ ] Support vsync attribute in `WindowConfig`
- [ ] Test vsync for all window types and platforms
- [ ] Document what window types support vsync
- [ ] Document additional OS specific steps needed to affect vsync settings if needed

**Comment by einarf** [comment]
Added vsync to `WindowConfig` in b2add0258f184e2e5fc03624086d74e2773f2e7d

this should be possible when 2.1 is out
```python
class MyThing(WindowConfig):
    vsync = False
```

**Comment by einarf** [comment]
The glfw window should respect vsync settings now. All windows except pygame2 and tk supports this.

Of course this assumes you have support for vsync in drivers and they are configured to use the application settings.
