### ISSUE TITLE
Behaviour of escape-key (closing the window) is not easily modifiable 

### ISSUE THREAD

**Issue by frosenek** [moderngl/moderngl-window#55]
It's hardcoded in every implementation of the window class, which makes it hard to change.

Talking to @einarf I suggested two possible improvements:

1. Keep the behaviour for convenience in smaller snippets, but abstract it in a way that makes it easily overrideable or opt-in
2. Let the user implement this behaviour themselves, which would be common for windowing libraries

**Comment by einarf** [comment]
It also seems pyglet also maps `ESC` for exit by default. Easy enough to override.

I think the simplest solution is to expose an attribute for the exit key. `exit_key` would be `keys.ESC` by default and it can be set to `None` or any other valid key mapping.

**Comment by einarf** [comment]
Added the `exit_key` attribute. This allows disabling or redefining the exit key.

<img width="538" alt="Screenshot 2020-01-03 at 22 18 56" src="https://user-images.githubusercontent.com/5418180/71749917-1fef8c00-2e77-11ea-8df7-30108e2d49b4.png">

**Comment by einarf** [comment]
2.0.5 on PyPI now with the changes.
