### ISSUE TITLE
Imgui example doesn't respect RMB click

### ISSUE THREAD

**Issue by pavelkrupala** [moderngl/moderngl-window#77]
I would say, that in the newest examples/integration_imgui.py example is RMB not working

**Comment by einarf** [comment]
Here's the context menu stuff
![Capture](https://user-images.githubusercontent.com/5418180/80397657-c0e6d480-88b6-11ea-9782-229c76434c18.PNG)

**Comment by einarf** [comment]
fixed f0b859075264746b48d641ed4c8d0d7e97c42b0d
