### ISSUE TITLE
Look into ffmpeg integration (playback)

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl-window#87]
It would be nice to support ffmpeg/video playback. This is simply updating a texture per frame.

.. or at least fix the libav video player in examples.

**Comment by Leterax** [comment]
Would be awesome to have. Would this be added as a example or something else?

**Comment by einarf** [comment]
Prototype here: https://github.com/moderngl/moderngl-window/blob/master/examples/video.py

**Comment by einarf** [comment]
The prototype is already broken. Needs fixing

**Comment by Leterax** [comment]
Fixed in #207
