### ISSUE TITLE
using `Camera.set_position` with int arguments causes movement to bug out.

### ISSUE THREAD

**Issue by Leterax** [moderngl/moderngl-window#90]
Calling `self.camera.set_position(0, 5, 0)`  where `self.camera` is `KeyboardCamera(self.wnd.keys, aspect_ratio=self.wnd.aspect_ratio)` causes the movement to break, presumably because a int vector is passed instead of a float vector. However no error is thrown. Would be nice to have the function either convert to float or check the type.

**Comment by Leterax** [comment]
See https://github.com/moderngl/moderngl-window/pull/91 for a fix

**Comment by einarf** [comment]
Merged
