### ISSUE TITLE
No module named 'moderngl_window.context'

### ISSUE THREAD

**Issue by genekogan** [moderngl/moderngl-window#92]
Installed moderngl and moderngl_window from source on a Jetson Nano (aarch64). 

moderngl imports fine, but moderngl_window gives me this error upon import:

```
python -c "import moderngl_window as mglw"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gene/.local/share/virtualenvs/GlTest-kj-KD8Sl/lib/python3.6/site-packages/moderngl_window-2.2.0-py3.6.egg/moderngl_window/__init__.py", line 14, in <module>
ModuleNotFoundError: No module named 'moderngl_window.context'
```

Any idea how to fix?

**Comment by einarf** [comment]
But you can `import moderngl_window`?

The most common cause is that you have a script called `moderngl_window.py`.

**Comment by genekogan** [comment]
No I can't import it, as it gives me the error above. I do not have a script called `moderngl_window.py`.

**Comment by einarf** [comment]
Weird, Can you `pip freeze` and show me the moderng and moderngl-window version installed?

**Comment by genekogan** [comment]
```
moderngl==5.6.0
moderngl-window==2.2.0
```

One thing that might be a clue is when I install from source `python setup.py install`, everything appears to go smoothly except at the end.

```
Installed /home/gene/.local/share/virtualenvs/GlTest-kj-KD8Sl/lib/python3.6/site-packages/moderngl_window-2.2.0-py3.6.egg
Processing dependencies for moderngl-window==2.2.0
Searching for glcontext<3,>=2
Reading https://pypi.org/simple/glcontext/
No local packages or working download links found for glcontext<3,>=2
error: Could not find suitable distribution for Requirement.parse('glcontext<3,>=2')
```

Can't get the right version of `glcontext`? Is there a different way to install it?

**Comment by genekogan** [comment]
I ended up installing `glcontext` separately just doing `pip install glcontext` and now have `glcontext==1.0.1` in my packages, but I still get that error.

**Comment by einarf** [comment]
hmm. I'll take a look. I usually just `pip install -e .` to make the install editable.

**Comment by genekogan** [comment]
Ah, you were right. Just installing with pip instead of installing from source worked, and all the examples now work. Thanks for the quick response!

**Comment by einarf** [comment]
You normally use `pip` to install from source these days. `pip install .` (if `setup.py` is in cwd) or using `-e` (editable) mode. The old way was `python setup.py install` /`python setup.py develop`.

Still.. it's weird that would not work.. so I'll try locally.
