### ISSUE TITLE
imgui images don't correctly render

### ISSUE THREAD

**Issue by jrjbertram** [moderngl/moderngl-window#94]
Issue:  imgui images don't render correctly.  In discord discussion, we figured out that textures need to be drawn in the command loop.  The reproducer zip file contains a reproducer, a sample image, and a hack fix that we discussed.  It should be unzipped into the examples directory.

![image](https://user-images.githubusercontent.com/2137279/84571672-4a187480-ad5a-11ea-8ca6-413ec5112ee5.png)

Reproducer:

[reproducer.zip](https://github.com/moderngl/moderngl-window/files/4774819/reproducer.zip)

    C:\Users\josh\divQ\moderngl-window\examples>unzip -l reproducer.zip
    Archive:  reproducer.zip
      Length      Date    Time    Name
    ---------  ---------- -----   ----
         3835  2020-06-13 09:38   integration_imgui.py
            0  2020-06-13 09:32   data/
         8587  2020-06-13 09:42   ../moderngl_window/integrations/imgui.py
        20123  2020-06-13 09:32   data/fruit.jpg
    ---------                     -------
        32545                     4 files

**Comment by einarf** [comment]
Fixed. Example : https://github.com/moderngl/moderngl-window/blob/master/examples/integration_imgui_image.py
