### ISSUE TITLE
Cannot left click on ImGUI after mouse drag event.

### ISSUE THREAD

**Issue by totomobile43** [moderngl/moderngl-window#95]
https://github.com/moderngl/moderngl-window/blob/678528c77514bb717e60f6c47dbcf74f4f1f36ff/moderngl_window/integrations/imgui.py#L43

Steps to reproduce.
1. Run basic imgui integration code.
2. Right-click and drag (i.e. camera pan)
3. Try to left click on an imgui element (e.g. button, checkbox).

Expected behaviour -> buttons work
Actual behaviour -> nothing can be clicked.

After some debugging, in the mouse_drag_event() fnx, the middle button seems swapped with the right button, or at least has a different mapping than the other mouse event functions.

Reproduced on mac and windows.

**Comment by einarf** [comment]
Fixedi in 564af00a1b6bcade62c4a1de29607d580de23c5d

**Comment by einarf** [comment]
Released 2.2.2 with a fix : https://github.com/moderngl/moderngl-window/releases/tag/2.2.2

**Comment by totomobile43** [comment]
Wow that was fast. Works great now!
